export const dummyFreelancers = [
  {
    frId: "FID0001",
    name: "Abigya Abayneh",
    title: "Full-Stack Developer",
    email: "abigyabayneh@gmail.com",
    regDate: "14 Jun 2019",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0002",
    name: "Abrahale Tewle",
    title: "Mobile Developer",
    email: "abrahalehtewlee35@gmail.com",
    regDate: "14 Jun 2019",
    status: "Deleted",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0003",
    name: "Amir Musema",
    title: "Product & UI/UX Designer",
    email: "amirmusema@gmail.com",
    regDate: "14 Jun 2019",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0004",
    name: "Biniam Shiferaw",
    title: "Backend Developer",
    email: "seifubini@gmail.com",
    regDate: "14 Jun 2019",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0005",
    name: "Dawit Alemu",
    title: "Frontend Developer",
    email: "babialemu08@gmail.com",
    regDate: "14 Jun 2019",
    status: "Deleted",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0006",
    name: "Natnael Samuel",
    title: "UI/UX Designer",
    email: "natisami1219@gmail.com",
    regDate: "14 Jun 2019",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0007",
    name: "Berihun Hadis",
    title: "Mobile Developer",
    email: "berihunhadis@gmail.com",
    regDate: "14 Jun 2019",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0008",
    name: "Hana Tadesse",
    title: "Data Analyst",
    email: "hanatadesse@gmail.com",
    regDate: "15 Jun 2019",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0009",
    name: "Mulugeta Meles",
    title: "Graphic Designer",
    email: "mulugetameles@gmail.com",
    regDate: "16 Jun 2019",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0010",
    name: "Selamawit Tesfaye",
    title: "Content Writer",
    email: "selamawittesfaye@gmail.com",
    regDate: "17 Jun 2019",
    status: "Deleted",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0011",
    name: "Teddy Gebre",
    title: "SEO Specialist",
    email: "teddygebre@gmail.com",
    regDate: "18 Jun 2019",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0012",
    name: "Liya Abebe",
    title: "Digital Marketer",
    email: "liyaabebe@gmail.com",
    regDate: "19 Jun 2020",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0013",
    name: "Kedir Admasu",
    title: "Video Editor",
    email: "kediradmasu@gmail.com",
    regDate: "20 Jun 2020",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0014",
    name: "Fatma Mohammed",
    title: "Web Developer",
    email: "fatmamohammed@gmail.com",
    regDate: "21 Jun 2020",
    status: "Active",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0015",
    name: "Rashid Ali",
    title: "Software Engineer",
    email: "rashidali@gmail.com",
    regDate: "22 Jun 2020",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0016",
    name: "Mekdes Haile",
    title: "Brand Strategist",
    email: "mekdeshaile@gmail.com",
    regDate: "23 Jun 2020",
    status: "Deleted",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0017",
    name: "Jemal Abdi",
    title: "Copywriter",
    email: "jemalabdi@gmail.com",
    regDate: "24 Jun 2020",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0018",
    name: "Tinsae Beyene",
    title: "Mobile Developer",
    email: "tinasebeyene@gmail.com",
    regDate: "25 Jun 2020",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0019",
    name: "Nardos Selam",
    title: "System Administrator",
    email: "nardosselam@gmail.com",
    regDate: "26 Jun 2020",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0020",
    name: "Michael Assefa",
    title: "Database Developer",
    email: "michaelassefa@gmail.com",
    regDate: "27 Jun 2020",
    status: "Deleted",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0021",
    name: "Adenug Juma",
    title: "Network Engineer",
    email: "adenugjuma@gmail.com",
    regDate: "28 Jun 2021",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0022",
    name: "Hawi Kedir",
    title: "Software Developer",
    email: "hawikedir@gmail.com",
    regDate: "29 Jun 2021",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0023",
    name: "Katrina Tesfaye",
    title: "Product Manager",
    email: "katrinatesfaye@gmail.com",
    regDate: "30 Jun 2021",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0024",
    name: "Yared Mulu",
    title: "Sales Executive",
    email: "yaredmulu@gmail.com",
    regDate: "1 Jul 2021",
    status: "Active",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0025",
    name: "Abebe Marga",
    title: "Customer Support",
    email: "abebemarga@gmail.com",
    regDate: "2 Jul 2021",
    status: "Deleted",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0026",
    name: "Ayalew Amde",
    title: "IT Support",
    email: "ayalewamde@gmail.com",
    regDate: "3 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0027",
    name: "Dagmawi Meles",
    title: "Cloud Engineer",
    email: "dagmawimeles@gmail.com",
    regDate: "4 Jul 2022",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0028",
    name: "Lulit Abdi",
    title: "UX Researcher",
    email: "lulitabdi@gmail.com",
    regDate: "5 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0029",
    name: "Federal Fikru",
    title: "DevOps Engineer",
    email: "federalfikru@gmail.com",
    regDate: "6 Jul 2022",
    status: "Deleted",
    skillLevel: "Expert",
  },
  {
    frId: "FID0030",
    name: "Noah Berhanu",
    title: "Web Designer",
    email: "noahberhanu@gmail.com",
    regDate: "7 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0031",
    name: "Selam Fikremariam",
    title: "Copy Editor",
    email: "selamfikremariam@gmail.com",
    regDate: "8 Jul 2022",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0032",
    name: "Kassim Derbew",
    title: "Mobile Application Developer",
    email: "kassimderbew@gmail.com",
    regDate: "9 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0033",
    name: "Firdaws Khalid",
    title: "Quality Assurance",
    email: "firdawskhalid@gmail.com",
    regDate: "10 Jul 2022",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0034",
    name: "Hailu Beyene",
    title: "E-commerce Specialist",
    email: "hailubeyene@gmail.com",
    regDate: "11 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0035",
    name: "Saron Abbad",
    title: "Game Developer",
    email: "saronabbad@gmail.com",
    regDate: "12 Jul 2022",
    status: "Deleted",
    skillLevel: "Expert",
  },
  {
    frId: "FID0036",
    name: "Biniyam Derese",
    title: "Blockchain Developer",
    email: "biniyamderese@gmail.com",
    regDate: "13 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0037",
    name: "Kepler Fido",
    title: "Penetration Tester",
    email: "keplerfido@gmail.com",
    regDate: "14 Jul 2022",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0038",
    name: "Tigist Regas",
    title: "System Analyst",
    email: "tigistregas@gmail.com",
    regDate: "15 Jul 2022",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0039",
    name: "Samir Farah",
    title: "Data Scientist",
    email: "samirfarah@gmail.com",
    regDate: "16 Jul 2023",
    status: "Deleted",
    skillLevel: "Expert",
  },
  {
    frId: "FID0040",
    name: "Hussein Nima",
    title: "IT Consultant",
    email: "husseinnima@gmail.com",
    regDate: "17 Jul 2023",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0041",
    name: "Amina Ahmed",
    title: "HR Specialist",
    email: "aminaahmed@gmail.com",
    regDate: "18 Jul 2023",
    status: "Active",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0042",
    name: "Kebede Goitom",
    title: "Infrastructure Engineer",
    email: "kebedegoitom@gmail.com",
    regDate: "19 Jul 2023",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0043",
    name: "Besret Hagos",
    title: "Technical Writer",
    email: "besrethagos@gmail.com",
    regDate: "20 Jul 2023",
    status: "Deleted",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0044",
    name: "Mekdes Abiy",
    title: "Localization Specialist",
    email: "mekdesabiy@gmail.com",
    regDate: "21 Jul 2024",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0045",
    name: "Hanan Samora",
    title: "Pen Tester",
    email: "hanansamora@gmail.com",
    regDate: "22 Jul 2024",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0046",
    name: "Meles Mulu",
    title: "SEO Consultant",
    email: "melesmulu@gmail.com",
    regDate: "23 Jul 2024",
    status: "Active",
    skillLevel: "Expert",
  },
  {
    frId: "FID0047",
    name: "Tassew Abate",
    title: "IT Manager",
    email: "tassewabate@gmail.com",
    regDate: "24 Jul 2024",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0048",
    name: "Sami Ahmed",
    title: "Support Engineer",
    email: "sami.ahmed@gmail.com",
    regDate: "25 Jul 2024",
    status: "Deleted",
    skillLevel: "Beginner",
  },
  {
    frId: "FID0049",
    name: "Radmila Hailu",
    title: "Java Developer",
    email: "radmilahailu@gmail.com",
    regDate: "26 Jul 2024",
    status: "Active",
    skillLevel: "Intermediate",
  },
  {
    frId: "FID0050",
    name: "Zain Abdi",
    title: "Python Developer",
    email: "zainabdi@gmail.com",
    regDate: "27 Jul 2025",
    status: "Active",
    skillLevel: "Expert",
  },
];
