export const dummyAPGSPPTSCP = [
  {
    pageId: "about",
    pageTitle: "About",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Jan 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "07 Sep 2022",
        content: "",
      },
      {
        id: 3,
        iteration: "3",
        updatedBy: "Muruts Yifter",
        updatedOn: "15 Oct 2023",
        content: "",
      },
    ],
  },
  {
    pageId: "pricing",
    pageTitle: "Pricing",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Jun 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2022",
        content: "",
      },
      {
        id: 3,
        iteration: "3",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Dec 2023",
        content: "",
      },
    ],
  },
  {
    pageId: "getting-started",
    pageTitle: "Getting started",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 May 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2022",
        content: "",
      },
      {
        id: 3,
        iteration: "3",
        updatedBy: "Muruts Yifter",
        updatedOn: "20 Aug 2023",
        content: "",
      },
      {
        id: 4,
        iteration: "4",
        updatedBy: "Muruts Yifter",
        updatedOn: "15 Sep 2024",
        content: "",
      },
    ],
  },
  {
    pageId: "privacy-policy",
    pageTitle: "Privacy Policy",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Jun 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2022",
        content: "",
      },
      {
        id: 3,
        iteration: "3",
        updatedBy: "Muruts Yifter",
        updatedOn: "20 Jul 2023",
        content: "",
      },
    ],
  },
  {
    pageId: "terms-of-service",
    pageTitle: "Terms of Service",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Apr 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2022",
        content: "",
      },
      {
        id: 3,
        iteration: "3",
        updatedBy: "Muruts Yifter",
        updatedOn: "30 Aug 2023",
        content: "",
      },
      {
        id: 4,
        iteration: "4",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Oct 2024",
        content: "",
      },
      {
        id: 5,
        iteration: "5",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2025",
        content: "",
      },
    ],
  },
  {
    pageId: "cookie-policy",
    pageTitle: "Cookie Policy",
    iterations: [
      {
        id: 1,
        iteration: "1",
        updatedBy: "Muruts Yifter",
        updatedOn: "01 Jun 2021",
        content: "",
      },
      {
        id: 2,
        iteration: "2",
        updatedBy: "Muruts Yifter",
        updatedOn: "14 Jun 2022",
        content: "",
      },
    ],
  },
];
