export const dummyJobPosts = [
  {
    id: "JID0001",
    title: "Senior mobile app developer",
    company: "Kepler Inc.",
    applicants: 5,
    postDate: "14 Jun 2020",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "cross-platform-mobile-development",
    tags: [
      "Mobile Development",
      "React Native",
      "Flutter",
      "iOS",
      "Android",
      "Cross-Platform",
      "Expert",
    ],
  },
  {
    id: "JID0002",
    title: "Product and UI/UX designer",
    company: "Kepler Inc.",
    applicants: 11,
    postDate: "14 Jun 2020",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-design",
    tags: [
      "UI/UX Design",
      "Figma",
      "Adobe XD",
      "Wireframing",
      "User Research",
      "Prototyping",
      "Intermediate",
    ],
  },
  {
    id: "JID0003",
    title: "Backend developer using FastAPI",
    company: "Flying Co.",
    applicants: 2,
    postDate: "14 Jun 2020",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "backend-development",
    tags: [
      "Backend Development",
      "FastAPI",
      "Python",
      "REST APIs",
      "PostgreSQL",
      "Microservices",
      "Intermediate",
    ],
  },
  {
    id: "JID0004",
    title: "Software Engineer I",
    company: "Kepler Inc.",
    applicants: 7,
    postDate: "14 Jun 2021",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Beginner",
    jobType: "Part-time",
    category: "software-engineering",
    tags: [
      "Software Engineering",
      "Java",
      "OOP",
      "Debugging",
      "Unit Testing",
      "Version Control",
      "Beginner",
    ],
  },
  {
    id: "JID0005",
    title: "Full-Stack web developer",
    company: "Flying Co.",
    applicants: 17,
    postDate: "14 Jun 2021",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "full-stack-development",
    tags: [
      "Full Stack",
      "React",
      "Node.js",
      "MERN Stack",
      "TypeScript",
      "REST APIs",
      "Expert",
    ],
  },
  {
    id: "JID0006",
    title: "Software quality assurance analyst",
    company: "Kepler Inc.",
    applicants: 0,
    postDate: "14 Jun 2021",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Intermediate",
    jobType: "Temporary",
    category: "quality-assurance",
    tags: [
      "QA Testing",
      "Selenium",
      "Test Cases",
      "Automation",
      "Bug Tracking",
      "Regression Testing",
      "Intermediate",
    ],
  },
  {
    id: "JID0007",
    title: "UI developer",
    company: "Flying Co.",
    applicants: 21,
    postDate: "14 Jun 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "ui-ux-design",
    tags: [
      "UI Development",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Responsive Design",
      "Accessibility",
      "Expert",
    ],
  },
  {
    id: "JID0008",
    title: "Data Scientist",
    company: "Tech Solutions Ltd.",
    applicants: 3,
    postDate: "15 Jul 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "data-science",
    tags: [
      "Data Science",
      "Python",
      "Machine Learning",
      "Pandas",
      "NumPy",
      "Data Visualization",
      "Intermediate",
    ],
  },
  {
    id: "JID0009",
    title: "DevOps Engineer",
    company: "Cloudify Inc.",
    applicants: 10,
    postDate: "16 Jul 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Per-diem",
    category: "cloud-computing",
    tags: [
      "DevOps",
      "AWS",
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Infrastructure as Code",
      "Expert",
    ],
  },
  {
    id: "JID0010",
    title: "Cybersecurity Analyst",
    company: "SecureTech Ltd.",
    applicants: 4,
    postDate: "17 Jul 2022",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Intermediate",
    jobType: "Contract",
    category: "cybersecurity",
    tags: [
      "Cybersecurity",
      "Network Security",
      "SIEM",
      "Penetration Testing",
      "Firewalls",
      "Incident Response",
      "Intermediate",
    ],
  },
  {
    id: "JID0011",
    title: "Systems Administrator",
    company: "Network Solutions Inc.",
    applicants: 8,
    postDate: "18 Jul 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Per-diem",
    category: "it-administration",
    tags: [
      "System Administration",
      "Linux",
      "Windows Server",
      "Active Directory",
      "Virtualization",
      "Troubleshooting",
      "Intermediate",
    ],
  },
  {
    id: "JID0012",
    title: "Project Manager",
    company: "Global Projects LLC",
    applicants: 12,
    postDate: "19 Jul 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "project-management",
    tags: [
      "Project Management",
      "Agile",
      "Scrum",
      "JIRA",
      "Risk Management",
      "Team Leadership",
      "Expert",
    ],
  },
  {
    id: "JID0013",
    title: "Technical Writer",
    company: "WriteItRight Inc.",
    applicants: 2,
    postDate: "20 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Beginner",
    jobType: "Part-time",
    category: "technical-writing",
    tags: [
      "Technical Writing",
      "Documentation",
      "API Guides",
      "Markdown",
      "User Manuals",
      "Git",
      "Beginner",
    ],
  },
  {
    id: "JID0014",
    title: "Machine Learning Engineer",
    company: "IntelliTech Corp.",
    applicants: 6,
    postDate: "21 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "machine-learning",
    tags: [
      "Machine Learning",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "NLP",
      "Computer Vision",
      "Expert",
    ],
  },
  {
    id: "JID0015",
    title: "Cloud Solutions Architect",
    company: "SkyNet Services",
    applicants: 5,
    postDate: "22 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "cloud-computing",
    tags: [
      "Cloud Architecture",
      "AWS",
      "Azure",
      "GCP",
      "Serverless",
      "Cloud Security",
      "Intermediate",
    ],
  },
  {
    id: "JID0016",
    title: "Content Strategist",
    company: "Creative Minds Agency",
    applicants: 1,
    postDate: "23 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Beginner",
    jobType: "Temporary",
    category: "content-strategy",
    tags: [
      "Content Strategy",
      "SEO",
      "Content Marketing",
      "Copywriting",
      "Brand Voice",
      "CMS",
      "Beginner",
    ],
  },
  {
    id: "JID0017",
    title: "Database Administrator",
    company: "DataCorp Solutions",
    applicants: 15,
    postDate: "24 Jul 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "database-development",
    tags: [
      "Database Administration",
      "SQL",
      "NoSQL",
      "MySQL",
      "Query Optimization",
      "Database Security",
      "Expert",
    ],
  },
  {
    id: "JID0018",
    title: "Frontend Developer",
    company: "Tech Innovators",
    applicants: 20,
    postDate: "25 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Per-diem",
    category: "frontend-development",
    tags: [
      "Frontend Development",
      "React",
      "JavaScript",
      "CSS",
      "UI Implementation",
      "Responsive Design",
      "Intermediate",
    ],
  },
  {
    id: "JID0019",
    title: "Business Analyst",
    company: "Visionary Analytics",
    applicants: 9,
    postDate: "26 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Part-time",
    category: "business-analysis",
    tags: [
      "Business Analysis",
      "Requirements Gathering",
      "Process Modeling",
      "SQL",
      "Tableau",
      "Stakeholder Management",
      "Intermediate",
    ],
  },
  {
    id: "JID0020",
    title: "SEO Specialist",
    company: "Digital Growth LLC",
    applicants: 3,
    postDate: "27 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Beginner",
    jobType: "Contract",
    category: "seo",
    tags: [
      "SEO",
      "Keyword Research",
      "Google Analytics",
      "On-Page SEO",
      "Link Building",
      "SEMrush",
      "Beginner",
    ],
  },
  {
    id: "JID0021",
    title: "Marketing Manager",
    company: "Marketing Wizards",
    applicants: 10,
    postDate: "28 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "marketing",
    tags: [
      "Digital Marketing",
      "Campaign Management",
      "Social Media",
      "Brand Strategy",
      "Market Research",
      "ROI Analysis",
      "Expert",
    ],
  },
  {
    id: "JID0022",
    title: "Cloud Engineer",
    company: "Cloud Solutions Group",
    applicants: 12,
    postDate: "29 Jul 2023",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "cloud-computing",
    tags: [
      "Cloud Engineering",
      "AWS",
      "Terraform",
      "CI/CD",
      "Cloud Migration",
      "Monitoring",
      "Intermediate",
    ],
  },
  {
    id: "JID0023",
    title: "Game Developer",
    company: "Epic Games",
    applicants: 8,
    postDate: "30 Jul 2024",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Expert",
    jobType: "Temporary",
    category: "game-development",
    tags: [
      "Game Development",
      "Unity",
      "C#",
      "3D Modeling",
      "Game Physics",
      "Multiplayer Networking",
      "Expert",
    ],
  },
  {
    id: "JID0024",
    title: "Application Support Analyst",
    company: "Services Inc.",
    applicants: 4,
    postDate: "31 Jul 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "it-support",
    tags: [
      "Application Support",
      "Troubleshooting",
      "Ticketing Systems",
      "SQL",
      "Customer Service",
      "Incident Management",
      "Intermediate",
    ],
  },
  {
    id: "JID0025",
    title: "Network Engineer",
    company: "Tech Connections",
    applicants: 7,
    postDate: "1 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Intermediate",
    jobType: "Part-time",
    category: "network-engineering",
    tags: [
      "Network Engineering",
      "Cisco",
      "TCP/IP",
      "Routing",
      "Firewalls",
      "Network Security",
      "Intermediate",
    ],
  },
  {
    id: "JID0026",
    title: "Research Scientist",
    company: "Bio Medics Corp.",
    applicants: 2,
    postDate: "2 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "research-science",
    tags: [
      "Research Science",
      "Data Analysis",
      "Statistical Modeling",
      "Python",
      "R",
      "Experimental Design",
      "Expert",
    ],
  },
  {
    id: "JID0027",
    title: "Mobile UI/UX Designer",
    company: "Pixel Perfect",
    applicants: 5,
    postDate: "3 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-design",
    tags: [
      "Mobile Design",
      "UI/UX",
      "Prototyping",
      "User Flows",
      "Material Design",
      "iOS Human Interface",
      "Intermediate",
    ],
  },
  {
    id: "JID0028",
    title: "Network Security Specialist",
    company: "Secure Networks",
    applicants: 6,
    postDate: "4 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Expert",
    jobType: "Part-time",
    category: "cybersecurity",
    tags: [
      "Network Security",
      "Firewalls",
      "IDS/IPS",
      "VPN",
      "Penetration Testing",
      "Security Audits",
      "Expert",
    ],
  },
  {
    id: "JID0029",
    title: "Web Scraping Developer",
    company: "Data Harvesters",
    applicants: 4,
    postDate: "5 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "web-development",
    tags: [
      "Web Scraping",
      "Python",
      "BeautifulSoup",
      "Selenium",
      "Data Extraction",
      "APIs",
      "Intermediate",
    ],
  },
  {
    id: "JID0030",
    title: "Marketing Director",
    company: "Global Ventures",
    applicants: 5,
    postDate: "6 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "marketing",
    tags: [
      "Marketing Strategy",
      "Brand Management",
      "Digital Advertising",
      "Budget Planning",
      "Team Leadership",
      "Market Analysis",
      "Expert",
    ],
  },
  {
    id: "JID0031",
    title: "IT Support Specialist",
    company: "QuickTech Solutions",
    applicants: 12,
    postDate: "7 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "it-support",
    tags: [
      "IT Support",
      "Help Desk",
      "Troubleshooting",
      "Hardware Setup",
      "Software Installation",
      "Remote Support",
      "Intermediate",
    ],
  },
  {
    id: "JID0032",
    title: "Financial Analyst",
    company: "Fiscal Insights",
    applicants: 3,
    postDate: "8 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Beginner",
    jobType: "Part-time",
    category: "finance",
    tags: [
      "Financial Analysis",
      "Excel",
      "Financial Modeling",
      "Budgeting",
      "Data Visualization",
      "Forecasting",
      "Beginner",
    ],
  },
  {
    id: "JID0033",
    title: "UI/UX Researcher",
    company: "UserFirst Designs",
    applicants: 2,
    postDate: "9 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skillLevel: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-research",
    tags: [
      "UX Research",
      "User Interviews",
      "Surveys",
      "Persona Development",
      "Usability Testing",
      "Data Synthesis",
      "Intermediate",
    ],
  },
  {
    id: "JID0034",
    title: "Cloud Data Architect",
    company: "DataConnect",
    applicants: 6,
    postDate: "10 Aug 2024",
    status: "Active",
    action: "Active",
    skillLevel: "Expert",
    jobType: "Fulltime",
    category: "cloud-computing",
    tags: [
      "Data Architecture",
      "Big Data",
      "AWS Redshift",
      "Data Lakes",
      "ETL",
      "Data Governance",
      "Expert",
    ],
  },
  {
    id: "JID0035",
    title: "API Developer",
    company: "TechFusion",
    applicants: 4,
    postDate: "11 Aug 2022",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Fulltime",
    category: "backend-development",
    tags: [
      "API Development",
      "RESTful APIs",
      "Swagger",
      "Postman",
      "OAuth",
      "Microservices",
      "Intermediate",
    ],
  },
  {
    id: "JID0036",
    title: "Business Development Manager",
    company: "Growth Partners",
    applicants: 7,
    postDate: "12 Aug 2020",
    status: "Active",
    action: "Active",
    skillLevel: "Intermediate",
    jobType: "Part-time",
    category: "business-development",
    tags: [
      "Business Development",
      "Sales Strategies",
      "Market Research",
      "Client Acquisition",
      "Negotiation",
      "Partnerships",
      "Intermediate",
    ],
  },
];
