export const dummyJobPosts = [
  {
    id: "JID0001",
    title: "Senior mobile app developer",
    company: "Kepler Inc.",
    applicants: 5,
    postDate: "14 Jun 2020",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "cross-platform-mobile-development",
  },
  {
    id: "JID0002",
    title: "Product and UI/UX designer",
    company: "Kepler Inc.",
    applicants: 11,
    postDate: "14 Jun 2020",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-design",
  },
  {
    id: "JID0003",
    title: "Backend developer using FastAPI",
    company: "Flying Co.",
    applicants: 2,
    postDate: "14 Jun 2020",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "backend-development",
  },
  {
    id: "JID0004",
    title: "Software Engineer I",
    company: "Kepler Inc.",
    applicants: 7,
    postDate: "14 Jun 2021",
    status: "Inactive",
    action: "Deactivated",
    skills: "Beginner",
    jobType: "Part-time",
    category: "software-engineering",
  },
  {
    id: "JID0005",
    title: "Full-Stack web developer",
    company: "Flying Co.",
    applicants: 17,
    postDate: "14 Jun 2021",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "full-stack-development",
  },
  {
    id: "JID0006",
    title: "Software quality assurance analyst",
    company: "Kepler Inc.",
    applicants: 0,
    postDate: "14 Jun 2021",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Temporary",
    category: "quality-assurance",
  },
  {
    id: "JID0007",
    title: "UI developer",
    company: "Flying Co.",
    applicants: 21,
    postDate: "14 Jun 2023",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "ui-ux-design",
  },
  {
    id: "JID0008",
    title: "Data Scientist",
    company: "Tech Solutions Ltd.",
    applicants: 3,
    postDate: "15 Jul 2022",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "data-science",
  },
  {
    id: "JID0009",
    title: "DevOps Engineer",
    company: "Cloudify Inc.",
    applicants: 10,
    postDate: "16 Jul 2022",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Per-project",
    category: "cloud-computing",
  },
  {
    id: "JID0010",
    title: "Cybersecurity Analyst",
    company: "SecureTech Ltd.",
    applicants: 4,
    postDate: "17 Jul 2022",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Contract",
    category: "cybersecurity",
  },
  {
    id: "JID0011",
    title: "Systems Administrator",
    company: "Network Solutions Inc.",
    applicants: 8,
    postDate: "18 Jul 2022",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Per-project",
    category: "it-administration",
  },
  {
    id: "JID0012",
    title: "Project Manager",
    company: "Global Projects LLC",
    applicants: 12,
    postDate: "19 Jul 2022",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "project-management",
  },
  {
    id: "JID0013",
    title: "Technical Writer",
    company: "WriteItRight Inc.",
    applicants: 2,
    postDate: "20 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skills: "Beginner",
    jobType: "Part-time",
    category: "technical-writing",
  },
  {
    id: "JID0014",
    title: "Machine Learning Engineer",
    company: "IntelliTech Corp.",
    applicants: 6,
    postDate: "21 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "machine-learning",
  },
  {
    id: "JID0015",
    title: "Cloud Solutions Architect",
    company: "SkyNet Services",
    applicants: 5,
    postDate: "22 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "cloud-computing",
  },
  {
    id: "JID0016",
    title: "Content Strategist",
    company: "Creative Minds Agency",
    applicants: 1,
    postDate: "23 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skills: "Beginner",
    jobType: "Temporary",
    category: "content-strategy",
  },
  {
    id: "JID0017",
    title: "Database Administrator",
    company: "DataCorp Solutions",
    applicants: 15,
    postDate: "24 Jul 2022",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "database-development",
  },
  {
    id: "JID0018",
    title: "Frontend Developer",
    company: "Tech Innovators",
    applicants: 20,
    postDate: "25 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Per-project",
    category: "frontend-development",
  },
  {
    id: "JID0019",
    title: "Business Analyst",
    company: "Visionary Analytics",
    applicants: 9,
    postDate: "26 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Part-time",
    category: "business-analysis",
  },
  {
    id: "JID0020",
    title: "SEO Specialist",
    company: "Digital Growth LLC",
    applicants: 3,
    postDate: "27 Jul 2023",
    status: "Inactive",
    action: "Deactivated",
    skills: "Beginner",
    jobType: "Contract",
    category: "seo",
  },
  {
    id: "JID0021",
    title: "Marketing Manager",
    company: "Marketing Wizards",
    applicants: 10,
    postDate: "28 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "marketing",
  },

  {
    id: "JID0022",
    title: "Cloud Engineer",
    company: "Cloud Solutions Group",
    applicants: 12,
    postDate: "29 Jul 2023",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "cloud-computing",
  },
  {
    id: "JID0023",
    title: "Game Developer",
    company: "Epic Games",
    applicants: 8,
    postDate: "30 Jul 2024",
    status: "Inactive",
    action: "Deactivated",
    skills: "Expert",
    jobType: "Temporary",
    category: "game-development",
  },
  {
    id: "JID0024",
    title: "Application Support Analyst",
    company: "Services Inc.",
    applicants: 4,
    postDate: "31 Jul 2024",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "it-support",
  },
  {
    id: "JID0025",
    title: "Network Engineer",
    company: "Tech Connections",
    applicants: 7,
    postDate: "1 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Part-time",
    category: "network-engineering",
  },
  {
    id: "JID0026",
    title: "Research Scientist",
    company: "Bio Medics Corp.",
    applicants: 2,
    postDate: "2 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "research-science",
  },
  {
    id: "JID0027",
    title: "Mobile UI/UX Designer",
    company: "Pixel Perfect",
    applicants: 5,
    postDate: "3 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-design",
  },
  {
    id: "JID0028",
    title: "Network Security Specialist",
    company: "Secure Networks",
    applicants: 6,
    postDate: "4 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skills: "Expert",
    jobType: "Part-time",
    category: "cybersecurity",
  },
  {
    id: "JID0029",
    title: "Web Scraping Developer",
    company: "Data Harvesters",
    applicants: 4,
    postDate: "5 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "web-development",
  },
  {
    id: "JID0030",
    title: "Marketing Director",
    company: "Global Ventures",
    applicants: 5,
    postDate: "6 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skills: "Expert",
    jobType: "Fulltime",
    category: "marketing",
  },
  {
    id: "JID0031",
    title: "IT Support Specialist",
    company: "QuickTech Solutions",
    applicants: 12,
    postDate: "7 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "it-support",
  },
  {
    id: "JID0032",
    title: "Financial Analyst",
    company: "Fiscal Insights",
    applicants: 3,
    postDate: "8 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Beginner",
    jobType: "Part-time",
    category: "finance",
  },
  {
    id: "JID0033",
    title: "UI/UX Researcher",
    company: "UserFirst Designs",
    applicants: 2,
    postDate: "9 Aug 2024",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Contract",
    category: "ui-ux-research",
  },
  {
    id: "JID0034",
    title: "Cloud Data Architect",
    company: "DataConnect",
    applicants: 6,
    postDate: "10 Aug 2024",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "cloud-computing",
  },
  {
    id: "JID0035",
    title: "API Developer",
    company: "TechFusion",
    applicants: 4,
    postDate: "11 Aug 2022",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "backend-development",
  },
  {
    id: "JID0036",
    title: "Business Development Manager",
    company: "Growth Partners",
    applicants: 7,
    postDate: "12 Aug 2020",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Part-time",
    category: "business-development",
  },
  {
    id: "JID0037",
    title: "Video Game Tester",
    company: "Interactive Entertainment",
    applicants: 15,
    postDate: "13 Aug 2020",
    status: "Inactive",
    action: "Deactivated",
    skills: "Beginner",
    jobType: "Temporary",
    category: "game-testing",
  },
  {
    id: "JID0038",
    title: "System Architect",
    company: "NextGen Tech",
    applicants: 3,
    postDate: "14 Aug 2020",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "software-architecture",
  },
  {
    id: "JID0039",
    title: "Help Desk Technician",
    company: "Tech Experts",
    applicants: 10,
    postDate: "15 Aug 2020",
    status: "Active",
    action: "Active",
    skills: "Beginner",
    jobType: "Part-time",
    category: "it-support",
  },
  {
    id: "JID0040",
    title: "Business Intelligence Analyst",
    company: "Insight Technologies",
    applicants: 9,
    postDate: "16 Aug 2020",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Contract",
    category: "business-intelligence",
  },
  {
    id: "JID0041",
    title: "UX Designer",
    company: "Design Hub",
    applicants: 6,
    postDate: "17 Aug 2022",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "ui-ux-design",
  },
  {
    id: "JID0042",
    title: "Data Analyst",
    company: "Data Insights",
    applicants: 8,
    postDate: "18 Aug 2021",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "data-analysis",
  },

  {
    id: "JID0043",
    title: "UX Researcher",
    company: "User Experience",
    applicants: 4,
    postDate: "19 Aug 2021",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "ui-ux-research",
  },
  {
    id: "JID0044",
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    applicants: 11,
    postDate: "20 Aug 2021",
    status: "Inactive",
    action: "Deactivated",
    skills: "Expert",
    jobType: "Contract",
    category: "cloud-computing",
  },
  {
    id: "JID0045",
    title: "Sales Manager",
    company: "Global Sales",
    applicants: 7,
    postDate: "21 Aug 2021",
    status: "Active",
    action: "Active",
    skills: "Expert",
    jobType: "Fulltime",
    category: "sales-marketing",
  },
  {
    id: "JID0046",
    title: "Data Engineer",
    company: "Data Solutions",
    applicants: 5,
    postDate: "22 Aug 2021",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "data-engineering",
  },
  {
    id: "JID0047",
    title: "Product Owner",
    company: "Agile Development",
    applicants: 3,
    postDate: "23 Aug 2021",
    status: "Inactive",
    action: "Deactivated",
    skills: "Expert",
    jobType: "Fulltime",
    category: "product-management",
  },
  {
    id: "JID0048",
    title: "Recruiter",
    company: "Talent Acquisition",
    applicants: 9,
    postDate: "24 Aug 2021",
    status: "Active",
    action: "Active",
    skills: "Intermediate",
    jobType: "Fulltime",
    category: "human-resources",
  },
  {
    id: "JID0049",
    title: "Social Media Manager",
    company: "Digital Marketing",
    applicants: 2,
    postDate: "25 Aug 2022",
    status: "Active",
    action: "Active",
    skills: "Beginner",
    jobType: "Part-time",
    category: "social-media-marketing",
  },
  {
    id: "JID0050",
    title: "Project Coordinator",
    company: "Project Management",
    applicants: 6,
    postDate: "26 Aug 2023",
    status: "Inactive",
    action: "Deactivated",
    skills: "Intermediate",
    jobType: "Contract",
    category: "project-management",
  },
];
