export const dummyFeedbacks = [
  {
    feId: "FDID001",
    message:
      "Thank you Sheqlee for helping me find a good job that i can work from my home. The opportunity i have gotten has given me the chance to supprot my family.",
    name: "Muruts Yifter",
    email: "muruts.yifter@gmail.com",
    regDate: "09 Jan 2020",
  },
  {
    feId: "FDID002",
    message: "Sheqlee helped me and my company to grow.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2020",
  },
  {
    feId: "FDID003",
    message: "The day I heard about Sheqlee is the most significant day.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2020",
  },
  {
    feId: "FDID004",
    message: "You know I am a Korean entrepreneur who has benefited greatly.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2020",
  },
  {
    feId: "FDID005",
    message: "Without Sheqlee I wouldn’t even be employed.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2021",
  },
  {
    feId: "FDID006",
    message: "Today I would like to take a moment to thank you.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2021",
  },
  {
    feId: "FDID007",
    message: "If it wasn’t for Sheqlee, I would be unemployed.",
    name: "Tedros Haile",
    email: "tedros.haile@gmail.com",
    regDate: "09 Jan 2021",
  },
  {
    feId: "FDID008",
    message: "Sheqlee made my job search much easier.",
    name: "Alice M.",
    email: "alice.m@example.com",
    regDate: "09 Jan 2022",
  },
  {
    feId: "FDID009",
    message: "I appreciate the support from the Sheqlee team.",
    name: "John D.",
    email: "john.d@example.com",
    regDate: "09 Jan 2022",
  },
  {
    feId: "FDID010",
    message: "Sheqlee has a user-friendly interface.",
    name: "Emma L.",
    email: "emma.l@example.com",
    regDate: "09 Jan 2022",
  },
  {
    feId: "FDID011",
    message: "Thanks to Sheqlee, I found my dream job.",
    name: "Alice M.",
    email: "alice.m@example.com",
    regDate: "09 Jan 2023",
  },
  {
    feId: "FDID012",
    message: "I highly recommend Sheqlee to others.",
    name: "David R.",
    email: "david.r@example.com",
    regDate: "09 Jan 2023",
  },
  {
    feId: "FDID013",
    message: "The feedback system is efficient.",
    name: "Sarah K.",
    email: "sarah.k@example.com",
    regDate: "09 Jan 2023",
  },
  {
    feId: "FDID014",
    message: "I love the variety of job listings.",
    name: "Michael J.",
    email: "michael.j@example.com",
    regDate: "09 Jan 2023",
  },
  {
    feId: "FDID015",
    message: "The notification system is very helpful.",
    name: "Sophia T.",
    email: "sophia.t@example.com",
    regDate: "09 Jan 2024",
  },
  {
    feId: "FDID016",
    message: "Sheqlee is changing the job market for the better.",
    name: "Alex B.",
    email: "alex.b@example.com",
    regDate: "09 Jan 2024",
  },
  {
    feId: "FDID017",
    message: "I feel more connected to my job prospects now.",
    name: "Liam O.",
    email: "liam.o@example.com",
    regDate: "09 Jan 2024",
  },
  {
    feId: "FDID018",
    message: "I am grateful for Sheqlee's assistance.",
    name: "Mia S.",
    email: "mia.s@example.com",
    regDate: "09 Jan 2024",
  },
  {
    feId: "FDID019",
    message: "The platform is excellent for freelancers.",
    name: "Noah W.",
    email: "noah.w@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID020",
    message: "Sheqlee has great features for job seekers.",
    name: "Olivia H.",
    email: "olivia.h@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID021",
    message: "I appreciate the easy application process.",
    name: "Ethan G.",
    email: "ethan.g@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID022",
    message: "Sheqlee has made networking easier.",
    name: "Ava C.",
    email: "ava.c@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID023",
    message: "The community support is fantastic.",
    name: "Isabella P.",
    email: "isabella.p@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID024",
    message: "I enjoy using Sheqlee for my freelance work.",
    name: "Lucas M.",
    email: "lucas.m@example.com",
    regDate: "09 Jan 2025",
  },
  {
    feId: "FDID025",
    message: "Sheqlee has been a game-changer for me.",
    name: "Amelia R.",
    email: "amelia.r@example.com",
    regDate: "09 Jan 2025",
  },
];
