export const dummyCategories = [
  {
    catId: "CTID001",
    title: "Web Frontend",
    tags: 11,
    jobs: 27,
    subs: 407,
    createdOn: "14 Jun 2019",
    status: "Active",
  },
  {
    catId: "CTID002",
    title: "Backend Development",
    tags: 7,
    jobs: 32,
    subs: 1024,
    createdOn: "14 Jun 2019",
    status: "Active",
  },
  {
    catId: "CTID003",
    title: "Mobile App Development",
    tags: 5,
    jobs: 10,
    subs: 879,
    createdOn: "14 Jun 2019",
    status: "Inactive",
  },
  {
    catId: "CTID004",
    title: "API Development",
    tags: 21,
    jobs: 7,
    subs: 2412,
    createdOn: "14 Jun 2019",
    status: "Active",
  },
  {
    catId: "CTID005",
    title: "Full-Stack Development",
    tags: 10,
    jobs: 43,
    subs: 102,
    createdOn: "14 Jun 2019",
    status: "Active",
  },
  {
    catId: "CTID006",
    title: "Progressive Web Apps Development",
    tags: 9,
    jobs: 113,
    subs: 710,
    createdOn: "14 Jun 2019",
    status: "Inactive",
  },
  {
    catId: "CTID007",
    title: "Hybrid Mobile App Development",
    tags: 15,
    jobs: 67,
    subs: 1578,
    createdOn: "14 Jun 2020",
    status: "Active",
  },
  {
    catId: "CTID008",
    title: "Machine Learning",
    tags: 30,
    jobs: 85,
    subs: 1200,
    createdOn: "01 Jul 2020",
    status: "Active",
  },
  {
    catId: "CTID009",
    title: "Data Science",
    tags: 25,
    jobs: 60,
    subs: 900,
    createdOn: "15 Jul 2020",
    status: "Inactive",
  },
  {
    catId: "CTID010",
    title: "Cloud Computing",
    tags: 18,
    jobs: 50,
    subs: 850,
    createdOn: "01 Aug 2020",
    status: "Active",
  },
  {
    catId: "CTID011",
    title: "DevOps",
    tags: 12,
    jobs: 35,
    subs: 600,
    createdOn: "02 Aug 2020",
    status: "Active",
  },
  {
    catId: "CTID012",
    title: "Cybersecurity",
    tags: 20,
    jobs: 40,
    subs: 470,
    createdOn: "05 Aug 2020",
    status: "Inactive",
  },
  {
    catId: "CTID013",
    title: "Game Development",
    tags: 16,
    jobs: 55,
    subs: 300,
    createdOn: "10 Aug 2021",
    status: "Active",
  },
  {
    catId: "CTID014",
    title: "Blockchain Development",
    tags: 14,
    jobs: 20,
    subs: 400,
    createdOn: "15 Aug 2021",
    status: "Active",
  },
  {
    catId: "CTID015",
    title: "Augmented Reality",
    tags: 22,
    jobs: 30,
    subs: 200,
    createdOn: "20 Aug 2021",
    status: "Inactive",
  },
  {
    catId: "CTID016",
    title: "Virtual Reality",
    tags: 19,
    jobs: 45,
    subs: 150,
    createdOn: "22 Aug 2021",
    status: "Active",
  },
  {
    catId: "CTID017",
    title: "UI/UX Design",
    tags: 8,
    jobs: 70,
    subs: 700,
    createdOn: "25 Aug 2021",
    status: "Active",
  },
  {
    catId: "CTID018",
    title: "E-commerce Development",
    tags: 6,
    jobs: 38,
    subs: 580,
    createdOn: "28 Aug 2022",
    status: "Inactive",
  },
  {
    catId: "CTID019",
    title: "SEO Optimization",
    tags: 4,
    jobs: 10,
    subs: 280,
    createdOn: "01 Sep 2022",
    status: "Active",
  },
  {
    catId: "CTID020",
    title: "Content Writing",
    tags: 2,
    jobs: 15,
    subs: 350,
    createdOn: "05 Sep 2022",
    status: "Active",
  },
  {
    catId: "CTID021",
    title: "Digital Marketing",
    tags: 9,
    jobs: 25,
    subs: 700,
    createdOn: "10 Sep 2022",
    status: "Active",
  },
  {
    catId: "CTID022",
    title: "Graphic Design",
    tags: 10,
    jobs: 32,
    subs: 850,
    createdOn: "15 Sep 2022",
    status: "Inactive",
  },
  {
    catId: "CTID023",
    title: "Social Media Management",
    tags: 6,
    jobs: 20,
    subs: 500,
    createdOn: "20 Sep 2023",
    status: "Active",
  },
  {
    catId: "CTID024",
    title: "Video Production",
    tags: 15,
    jobs: 18,
    subs: 400,
    createdOn: "25 Sep 2023",
    status: "Inactive",
  },
  {
    catId: "CTID025",
    title: "Web Hosting",
    tags: 11,
    jobs: 27,
    subs: 900,
    createdOn: "30 Sep 2023",
    status: "Active",
  },
  {
    catId: "CTID026",
    title: "Software Testing",
    tags: 5,
    jobs: 22,
    subs: 600,
    createdOn: "01 Oct 2023",
    status: "Active",
  },
  {
    catId: "CTID027",
    title: "Technical Support",
    tags: 8,
    jobs: 10,
    subs: 350,
    createdOn: "05 Oct 2023",
    status: "Inactive",
  },
  {
    catId: "CTID028",
    title: "IT Consulting",
    tags: 9,
    jobs: 17,
    subs: 420,
    createdOn: "10 Oct 2023",
    status: "Active",
  },
  {
    catId: "CTID029",
    title: "Database Management",
    tags: 12,
    jobs: 14,
    subs: 200,
    createdOn: "15 Oct 2023",
    status: "Inactive",
  },
  {
    catId: "CTID030",
    title: "Network Administration",
    tags: 10,
    jobs: 30,
    subs: 900,
    createdOn: "20 Oct 2024",
    status: "Active",
  },
];
