export const dummyCompanies = [
  {
    coID: "CID0001",
    companyName: "Jack Henry and Assoc.",
    email: "jack.henry@gmail.com",
    regDate: "14 Jun 2019",
    subs: 21,
    jobs: 7,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0002",
    companyName: "IDT Corporation",
    email: "idt.corp@gmail.com",
    regDate: "14 Jun 2019",
    subs: 78,
    jobs: 12,
    status: "Deleted",
    action: "Inactive",
  },
  {
    coID: "CID0003",
    companyName: "Otto",
    email: "otto@gmail.com",
    regDate: "14 Jun 2019",
    subs: 102,
    jobs: 5,
    status: "Active",
    action: "Inactive",
  },
  {
    coID: "CID0004",
    companyName: "Vrgl Inc.",
    email: "vrgl.inc@gmail.com",
    regDate: "14 Jun 2019",
    subs: 32,
    jobs: 1,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0005",
    companyName: "Tyler Technologies",
    email: "tyler.tech@gmail.com",
    regDate: "14 Jun 2019",
    subs: 51,
    jobs: 21,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0006",
    companyName: "Infosys",
    email: "infosys@gmail.com",
    regDate: "14 Jun 2020",
    subs: 11,
    jobs: 9,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0007",
    companyName: "C.H. Robinson",
    email: "ch.robison@gmail.com",
    regDate: "14 Jun 2020",
    subs: 3,
    jobs: 7,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0008",
    companyName: "Cloud Solutions",
    email: "cloud.solutions@gmail.com",
    regDate: "15 Jun 2020",
    subs: 50,
    jobs: 10,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0009",
    companyName: "Tech Innovations",
    email: "tech.innovations@gmail.com",
    regDate: "16 Jun 2020",
    subs: 63,
    jobs: 15,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0010",
    companyName: "Digital Ventures",
    email: "digital.ventures@gmail.com",
    regDate: "17 Jun 2020",
    subs: 45,
    jobs: 20,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0011",
    companyName: "NextGen Systems",
    email: "nextgen.systems@gmail.com",
    regDate: "18 Jun 2021",
    subs: 30,
    jobs: 8,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0012",
    companyName: "Innovate Corp",
    email: "innovate.corp@gmail.com",
    regDate: "19 Jun 2021",
    subs: 90,
    jobs: 25,
    status: "Active",
    action: "Deleted",
  },
  {
    coID: "CID0013",
    companyName: "Future Tech",
    email: "future.tech@gmail.com",
    regDate: "20 Jun 2021",
    subs: 53,
    jobs: 18,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0014",
    companyName: "Synergy Group",
    email: "synergy.group@gmail.com",
    regDate: "21 Jun 2021",
    subs: 70,
    jobs: 30,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0015",
    companyName: "Quantum Leap",
    email: "quantum.leap@gmail.com",
    regDate: "22 Jun 2021",
    subs: 40,
    jobs: 12,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0016",
    companyName: "Vertex Ltd",
    email: "vertex.ltd@gmail.com",
    regDate: "23 Jun 2022",
    subs: 22,
    jobs: 5,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0017",
    companyName: "Data Solutions",
    email: "data.solutions@gmail.com",
    regDate: "24 Jun 2022",
    subs: 65,
    jobs: 14,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0018",
    companyName: "Evolve Technologies",
    email: "evolve.tech@gmail.com",
    regDate: "25 Jun 2022",
    subs: 33,
    jobs: 11,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0019",
    companyName: "Eureka Inc.",
    email: "eureka.inc@gmail.com",
    regDate: "26 Jun 2022",
    subs: 88,
    jobs: 22,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0020",
    companyName: "Pinnacle Group",
    email: "pinnacle.group@gmail.com",
    regDate: "27 Jun 2022",
    subs: 56,
    jobs: 16,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0021",
    companyName: "Orbit Systems",
    email: "orbit.systems@gmail.com",
    regDate: "28 Jun 2022",
    subs: 47,
    jobs: 19,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0022",
    companyName: "Express Tech",
    email: "express.tech@gmail.com",
    regDate: "29 Jun 2023",
    subs: 72,
    jobs: 27,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0023",
    companyName: "Innovative Networks",
    email: "innovative.networks@gmail.com",
    regDate: "30 Jun 2023",
    subs: 36,
    jobs: 6,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0024",
    companyName: "TechSphere",
    email: "techsphere@gmail.com",
    regDate: "1 Jul 2023",
    subs: 29,
    jobs: 9,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0025",
    companyName: "Nova Solutions",
    email: "nova.solutions@gmail.com",
    regDate: "2 Jul 2023",
    subs: 81,
    jobs: 23,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0026",
    companyName: "Apex Innovations",
    email: "apex.innovations@gmail.com",
    regDate: "3 Jul 2023",
    subs: 58,
    jobs: 15,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0027",
    companyName: "Titan Tech",
    email: "titan.tech@gmail.com",
    regDate: "4 Jul 2023",
    subs: 73,
    jobs: 13,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0028",
    companyName: "Bright Future",
    email: "bright.future@gmail.com",
    regDate: "5 Jul 2023",
    subs: 65,
    jobs: 26,
    status: "Inactive",
    action: "Active",
  },
  {
    coID: "CID0029",
    companyName: "Alpha Technologies",
    email: "alpha.tech@gmail.com",
    regDate: "6 Jul 2023",
    subs: 40,
    jobs: 17,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0030",
    companyName: "Sapphire Systems",
    email: "sapphire.systems@gmail.com",
    regDate: "7 Jul 2023",
    subs: 23,
    jobs: 8,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0031",
    companyName: "Elite Services",
    email: "elite.services@gmail.com",
    regDate: "8 Jul 2023",
    subs: 90,
    jobs: 24,
    status: "Deleted",
    action: "Active",
  },
  {
    coID: "CID0032",
    companyName: "Platinum Innovations",
    email: "platinum.innovations@gmail.com",
    regDate: "9 Jul 2023",
    subs: 62,
    jobs: 12,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0033",
    companyName: "Zenith Group",
    email: "zenith.group@gmail.com",
    regDate: "10 Jul 2023",
    subs: 48,
    jobs: 20,
    status: "Inactive",
    action: "Active",
  },
  {
    coID: "CID0034",
    companyName: "Omega Tech",
    email: "omega.tech@gmail.com",
    regDate: "11 Jul 2023",
    subs: 34,
    jobs: 9,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0035",
    companyName: "Core Technologies",
    email: "core.tech@gmail.com",
    regDate: "12 Jul 2024",
    subs: 77,
    jobs: 28,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0036",
    companyName: "Nexus Systems",
    email: "nexus.systems@gmail.com",
    regDate: "13 Jul 2024",
    subs: 59,
    jobs: 14,
    status: "Deleted",
    action: "Inactive",
  },
  {
    coID: "CID0037",
    companyName: "Skyline Corp",
    email: "skyline.corp@gmail.com",
    regDate: "14 Jul 2024",
    subs: 42,
    jobs: 11,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0038",
    companyName: "Visionary Solutions",
    email: "visionary.solutions@gmail.com",
    regDate: "15 Jul 2024",
    subs: 85,
    jobs: 19,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0039",
    companyName: "Unity Technologies",
    email: "unity.tech@gmail.com",
    regDate: "16 Jul 2024",
    subs: 31,
    jobs: 7,
    status: "Deleted",
    action: "Inactive",
  },
  {
    coID: "CID0040",
    companyName: "Vanguard Innovations",
    email: "vanguard.innovations@gmail.com",
    regDate: "17 Jul 2024",
    subs: 93,
    jobs: 30,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0041",
    companyName: "Summit Tech",
    email: "summit.tech@gmail.com",
    regDate: "18 Jul 2025",
    subs: 54,
    jobs: 16,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0042",
    companyName: "Concord Solutions",
    email: "concord.solutions@gmail.com",
    regDate: "19 Jul 2025",
    subs: 38,
    jobs: 5,
    status: "Deleted",
    action: "Inactive",
  },
  {
    coID: "CID0043",
    companyName: "Inspire Technologies",
    email: "inspire.tech@gmail.com",
    regDate: "20 Jul 2018",
    subs: 71,
    jobs: 29,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0044",
    companyName: "Collaborative Group",
    email: "collaborative.group@gmail.com",
    regDate: "21 Jul 2018",
    subs: 60,
    jobs: 11,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0045",
    companyName: "Dynamic Solutions",
    email: "dynamic.solutions@gmail.com",
    regDate: "22 Jul 2018",
    subs: 43,
    jobs: 17,
    status: "Deleted",
    action: "Inactive",
  },
  {
    coID: "CID0046",
    companyName: "Elysium Tech",
    email: "elysium.tech@gmail.com",
    regDate: "23 Jul 2018",
    subs: 79,
    jobs: 15,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0047",
    companyName: "Galactic Systems",
    email: "galactic.systems@gmail.com",
    regDate: "24 Jul 2018",
    subs: 27,
    jobs: 10,
    status: "Active",
    action: "Active",
  },
  {
    coID: "CID0048",
    companyName: "Innovative Minds",
    email: "innovative.minds@gmail.com",
    regDate: "25 Jul 2018",
    subs: 66,
    jobs: 12,
    status: "Deleted",
    action: "Inactive",
  },
  //   {
  //     coID: "CID0049",
  //     companyName: "Epic Solutions",
  //     email: "epic.solutions@gmail.com",
  //     regDate: "26 Jul 2022",
  //     subs: 49,
  //     jobs: 6,
  //     status: "Active",
  //     action: "Active",
  //   },
  //   {
  //     coID: "CID0050",
  //     companyName: "Astro Tech",
  //     email: "astro.tech@gmail.com",
  //     regDate: "27 Jul 2022",
  //     subs: 86,
  //     jobs: 28,
  //     status: "Active",
  //     action: "Active",
  //   },
];
